//! MPC trusted setup ceremony for Groth16 proving keys.
//!
//! Replaces the single-source SRS produced by the existing
//! `setup_*_ceremony` binaries with a multi-party-computation
//! upgrade so no single party holds the toxic waste required to
//! forge proofs. Tracking issue:
//! <https://github.com/paraloom-labs/paraloom-core/issues/64>.
//!
//! ## Two-phase structure
//!
//! - **Phase 1.** The initial single-source SRS, generated by the
//!   existing `setup_withdrawal_ceremony` / `setup_*` binaries
//!   using `ark_std::rand::thread_rng()` (OS entropy, destroyed
//!   by the operator). Single-party trust at this stage.
//! - **Phase 2.** A multi-party-computation upgrade applied by N
//!   contributors, each sampling their own `δ_i` and applying the
//!   BGM17 contribution operation: `delta_after ← delta_before *
//!   δ_i` and the corresponding update of the `h_query`/`l_query`
//!   vectors. As long as one contributor in Phase 2 is honest and
//!   destroys their `δ_i`, no party knows the final `δ`.
//!
//! ## What Phase 2 does not do
//!
//! Phase 2 re-randomises `δ` and only `δ`. `α`, `β` and every
//! element derived from `τ` come out of Phase 1 and are carried
//! through the chain unchanged — the verifier requires exactly
//! that. So the contributions do not stand in for a Phase 1
//! ceremony: whoever produced the initial SRS can still forge
//! proofs afterwards, however many contributors join.
//! `phase1_trapdoor` demonstrates this end to end.
//!
//! A single-party Phase 1 therefore leaves soundness resting on
//! that one operator having destroyed their entropy. Removing
//! that assumption means starting the chain from a public
//! powers-of-tau transcript instead; see issue #659.
//!
//! ## Scope
//!
//! The v0.5.0 round ceremonied the separate privacy circuits
//! (`WithdrawCircuit` and `TransferCircuit` chains completed; see
//! `ceremony/withdraw/` and `ceremony/transfer/`). Circuit v3
//! (#350) replaced them with the unified `TransactCircuitV3`,
//! which is the settlement path on chain and therefore the
//! circuit the mainnet ceremony runs against (#659). A phase-2
//! chain is bound to one R1CS, so the finished v2 chains do not
//! carry over. The WASM compute layer (`ComputeCircuit`) stays
//! out of scope because its R1CS varies per job; see issue #64
//! for the rationale.
//!
//! ## Submodules
//!
//! - [`transcript`] — Phase 2 transcript data model: contribution
//!   chain, hash chain, serde wire format. Crypto-free.
//!
//! Subsequent submodules (BGM17 contribution operation,
//! verifier, contributor CLI) land as the implementation
//! progresses; each is scoped to one PR.

pub mod bgm17;
pub mod contribute;
#[cfg(test)]
mod phase1_trapdoor;
pub mod policy;
pub mod transcript;
pub mod verifier;

pub use bgm17::{
    apply_contribution, verify_contribution, verify_contribution_deltas, BgmError, DleqProof,
};
pub use contribute::{
    contribute, read_pk, read_transcript, write_compressed, write_pk, write_transcript,
    ContributeError,
};
pub use policy::{enforce_finalize_policy, FinalizePolicy, PolicyError};
pub use transcript::{
    hash_contribution, try_hash_from_hex, CircuitId, Contribution, Phase2Transcript,
    TranscriptError, TranscriptHash, TRANSCRIPT_VERSION,
};
pub use verifier::{
    verify_final_pk, verify_final_pk_consistency, verify_phase2_transcript, VerifyError,
};
