//! MPC trusted setup ceremony for Groth16 proving keys.
//!
//! Replaces the single-source SRS produced by the existing
//! `setup_*_ceremony` binaries with a multi-party-computation
//! upgrade so no single party holds the toxic waste required to
//! forge proofs. Tracking issue:
//! <https://github.com/paraloom-labs/paraloom-core/issues/64>.
//!
//! ## Two-phase structure
//!
//! - **Phase 1.** The initial single-source SRS, generated by the
//!   existing `setup_withdrawal_ceremony` / `setup_*` binaries
//!   using `ark_std::rand::thread_rng()` (OS entropy, destroyed
//!   by the operator). Single-party trust at this stage.
//! - **Phase 2.** A multi-party-computation upgrade applied by N
//!   contributors, each sampling their own `δ_i` and applying the
//!   BGM17 contribution operation: `delta_after ← delta_before *
//!   δ_i` and the corresponding update of the `h_query`/`l_query`
//!   vectors. As long as one contributor in Phase 2 is honest and
//!   destroys their `δ_i`, the ceremony is sound regardless of
//!   the Phase 1 trapdoor.
//!
//! ## Scope
//!
//! Three privacy circuits are ceremonied for v0.5.0:
//! `DepositCircuit`, `TransferCircuit`, `WithdrawCircuit`. The
//! WASM compute layer (`ComputeCircuit`) is out of scope because
//! its R1CS varies per job; see issue #64 for the rationale.
//!
//! ## Submodules
//!
//! - [`transcript`] — Phase 2 transcript data model: contribution
//!   chain, hash chain, serde wire format. Crypto-free.
//!
//! Subsequent submodules (BGM17 contribution operation,
//! verifier, contributor CLI) land as the implementation
//! progresses; each is scoped to one PR.

pub mod transcript;

pub use transcript::{
    hash_contribution, CircuitId, Contribution, Phase2Transcript, TranscriptError, TranscriptHash,
    TRANSCRIPT_VERSION,
};
